apiVersion: v1
kind: Secret
metadata:
  name: kafka-connection
  namespace: www-tomshley-com-contactnotify-service-namespace
data:
  hostname: $KAFKA_BROKER_SERVER_BASE64
  username: $KAFKA_CLUSTER_KEY_BASE64
  password: $KAFKA_CLUSTER_SECRET_BASE64
