apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: www-tomshley-com-contactnotify-service
  name: www-tomshley-com-contactnotify-service
  namespace: www-tomshley-com-contactnotify-service-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: www-tomshley-com-contactnotify-service
  template:
    metadata:
      labels:
        app: www-tomshley-com-contactnotify-service
        actorSystemName: www-tomshley-com-contactnotify-service
    spec:
      imagePullSecrets:
        - name: registry-credentials
      # If dedicated nodes and taints are required:
      # nodeSelector:
      #   cloud.google.com/gke-nodepool: www-tomshley-com-pool-contactsvc
      # tolerations:
      #   - key: "www-tomshley-com-pooltaintdedicated"
      #     operator: "Equal"
      #     value: "www-tomshley-com-pool-contactsvc-taint"
      #     effect: "NoSchedule"
      containers:
        - name: www-tomshley-com-contactnotify-service
          # use specific image version from docker publish
          image: registry.gitlab.com/tomshley/brands/usa/tomshleyllc/tech/www-tomshley-com-contactnotify-service/www-tomshley-com-contactnotify-service:0.0.0-18-1e7ee59a
          imagePullPolicy: IfNotPresent
          # these will need to be increased tuned for production environments!
          # Standard Akka Performance reference
          # resources:
          #  limits:
          #    memory: "2Gi"
          #  requests:
          #    memory: "2Gi"
          #    cpu: "1"

          readinessProbe:
            httpGet:
              path: "/ready"
              port: management
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 120
          livenessProbe:
            httpGet:
              path: "/alive"
              port: management
            periodSeconds: 20
            failureThreshold: 5
            initialDelaySeconds: 30
          ports:
            - name: grpc
              containerPort: 9900
              protocol: TCP
            - name: grpc-web
              containerPort: 8080
              protocol: TCP
            - name: remoting
              containerPort: 7355
              protocol: TCP
            - name: management
              containerPort: 7626
              protocol: TCP
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: REQUIRED_CONTACT_POINT_NR
              value: "2"
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:InitialRAMPercentage=75 -XX:MaxRAMPercentage=75"
            - name: APP_LABEL
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.labels['app']"
            - name: KAFKA_BROKER_SERVER
              valueFrom:
                secretKeyRef:
                  name: kafka-connection
                  key: hostname
            - name: KAFKA_CLUSTER_KEY
              valueFrom:
                secretKeyRef:
                  name: kafka-connection
                  key: username
            - name: KAFKA_CLUSTER_SECRET
              valueFrom:
                secretKeyRef:
                  name: kafka-connection
                  key: password
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  name: twilio-connection
                  key: account_sid
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: twilio-connection
                  key: auth_token
            - name: TWILIO_PHONE_NUMBER
              valueFrom:
                secretKeyRef:
                  name: twilio-connection
                  key: from_number
